
function [] = generateCharacterizationReport()

%% Generate report
import mlreportgen.dom.*;
import mlreportgen.report.*;

% Create Report (save to a local directory to avoid OneDrive issues)
rpt = Report('C:\Temp\MyReport','pdf');

% Title Page
titlePage = TitlePage;
titlePage.Title = sprintf('Charaterization of %s');
titlePage.Subtitle = 'Generated by MATLAB';
add(rpt, titlePage);

% Table of Contents
toc = TableOfContents;
add(rpt, toc);

% Helper Function: Generate and Resize Figures
    function imgFile = generateFigure(x, y, color, titleText, filename)
        fig = figure;
        plot(x, y, color, 'LineWidth', 1.5);
        xlabel('X-axis');
        ylabel('Y-axis');
        title(titleText);
        grid on;

        % Resize figure before saving
        set(fig, 'Units', 'Inches', 'Position', [0, 0, 5, 3]); % 5x3 inches

        % Save as a smaller PNG image (150 DPI for quality)
        print(fig, filename, '-dpng', '-r150');
        close(fig);
        imgFile = filename;
    end

% Chapter 1: Equalization Curve
ch1 = Chapter('Equalization Curve');
x1 = linspace(0, 10, 100);
y1 = log(x1 + 1);
img1 = generateFigure(x1, y1, 'r', 'Equalization Curve', 'equalization_curve.png');
imgObj1 = Image(img1); imgObj1.Width = '5in'; imgObj1.Height = '3in';
add(ch1, imgObj1);
add(ch1, Table([x1(:), y1(:)]));
add(rpt, ch1);

% Chapter 2: Power Curve
ch2 = Chapter('Power Curve');
x2 = linspace(0, 10, 100);
y2 = x2.^2;
img2 = generateFigure(x2, y2, 'b', 'Power Curve', 'power_curve.png');
imgObj2 = Image(img2); imgObj2.Width = '5in'; imgObj2.Height = '3in';
add(ch2, imgObj2);
add(ch2, Table([x2(:), y2(:)]));
add(rpt, ch2);

% Chapter 3: Focus Curve
ch3 = Chapter('Focus Curve');
x3 = linspace(0, 10, 100);
y3 = exp(-0.5 * (x3 - 5).^2);
img3 = generateFigure(x3, y3, 'g', 'Focus Curve', 'focus_curve.png');
imgObj3 = Image(img3); imgObj3.Width = '5in'; imgObj3.Height = '3in';
add(ch3, imgObj3);
add(ch3, Table([x3(:), y3(:)]));
add(rpt, ch3);

% Close Report
close(rpt);
rptview(rpt);  % Open report
end